// theme.js — all color tokens for dark and light modes.
// To add a new theme, add a new key here and pass it to useTheme.

export const themes = {
  dark: {
    bg:                  "#0a0c0f",
    cardBg:              "#0d1015",
    cardBorder:          "#161b22",
    tippingCardBorder:   "#1a3028",
    headerBorder:        "#1e2329",
    text:                "#d1e0d5",
    textMuted:           "#8093a0",
    textDim:             "#3d5248",
    metaLabel:           "#5a7a6b",
    metaValue:           "#8a9ea0",
    signalText:          "#648577",
    signalArrow:         "#587d6e",
    assetBg:             "#080c0e",
    assetBorder:         "#161b22",
    assetText:           "#5e927c",
    filterActiveBg:      "#0d1f17",
    filterActiveBorder:  "#2d5a42",
    filterActiveText:    "#5ab87e",
    filterBorder:        "#1e2329",
    filterText:          "#5a6872",
    searchBg:            "#111418",
    searchBorder:        "#1e2329",
    titleColor:          "#78a78f",
    subtitleColor:       "#e8eaed",
    countColor:          "#668c7a",
    divider:             "#161b22",
    toggleBg:            "#111418",
    toggleBorder:        "#22272f",
    toggleText:          "#7b868f",
  },
  light: {
    bg:                  "#f4f5f0",
    cardBg:              "#ffffff",
    cardBorder:          "#e2e4de",
    tippingCardBorder:   "#b8d4c4",
    headerBorder:        "#e2e4de",
    text:                "#1a2e24",
    textMuted:           "#7a8e84",
    textDim:             "#9aada4",
    metaLabel:           "#8aaa98",
    metaValue:           "#3a5248",
    signalText:          "#5a7a6a",
    signalArrow:         "#aac4b8",
    assetBg:             "#eef0eb",
    assetBorder:         "#d8ddd8",
    assetText:           "#3a6050",
    filterActiveBg:      "#e0f0e8",
    filterActiveBorder:  "#5a9a72",
    filterActiveText:    "#2a6a42",
    filterBorder:        "#d0d5cc",
    filterText:          "#7a8e84",
    searchBg:            "#ffffff",
    searchBorder:        "#d0d5cc",
    titleColor:          "#4a7a5a",
    subtitleColor:       "#1a2e24",
    countColor:          "#8aaa98",
    divider:             "#e8ebe4",
    toggleBg:            "#ffffff",
    toggleBorder:        "#d0d5cc",
    toggleText:          "#5a7a6a",
  },
};
